// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Panda) DeepCopyInto(out *Panda) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Panda.
func (in *Panda) DeepCopy() *Panda {
	if in == nil {
		return nil
	}
	out := new(Panda)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Panda) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandaList) DeepCopyInto(out *PandaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Panda, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandaList.
func (in *PandaList) DeepCopy() *PandaList {
	if in == nil {
		return nil
	}
	out := new(PandaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PandaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandaSpec) DeepCopyInto(out *PandaSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandaSpec.
func (in *PandaSpec) DeepCopy() *PandaSpec {
	if in == nil {
		return nil
	}
	out := new(PandaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandaStatus) DeepCopyInto(out *PandaStatus) {
	*out = *in
	if in.BambooConsumption != nil {
		in, out := &in.BambooConsumption, &out.BambooConsumption
		*out = new(int32)
		**out = **in
	}
	if in.AppetiteScale != nil {
		in, out := &in.AppetiteScale, &out.AppetiteScale
		*out = new(AppetiteScale)
		**out = **in
	}
	if in.WeightScale != nil {
		in, out := &in.WeightScale, &out.WeightScale
		*out = new(WeightScale)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandaStatus.
func (in *PandaStatus) DeepCopy() *PandaStatus {
	if in == nil {
		return nil
	}
	out := new(PandaStatus)
	in.DeepCopyInto(out)
	return out
}
